name = "toolneat"
compatibility_date = "2025-01-01"

[assets]
directory = "./"
not_found_handling = "404-page"
exclude = ["node_modules", ".git", ".idea", "src", "*.md", "package*.json", ".gitignore"]
